### PR TITLE
Change default port to 5017

### LINKED ISSUE #20: Issue with suggested port 5002
TL;DR: I'm having issues in using the suggested port in the examples `5002`, so it may make sense changing the port number to a less used one.

I'm on OSX, and if I `curl -I localhost:5002` I get
```
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, no-store, must-revalidate
Date: Thu, 20 Jun 2019 09:21:47 GMT
Content-Length: 23
Content-Type: text/plain; charset=utf-8
```
It seems there's some service already running on that port:
```
$ lsof -i TCP:5002
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
agent   10172 andrea   11u  IPv4 0x4b127be231ef2135      0t0  TCP localhost:rfe (LISTEN)
```

Doing a google search, port 5002 seems to be related to `radio free ethernet`, and this is documented in the [IANA port list](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5002):

```
rfe                5002        tcp    radio free ethernet
rfe                5002        udp    radio free ethernet
```

### PR DESCRIPTION
**Pull request by vfonic**
Fixes #20

This port number was selected on random from a port range 5016-5019.

More info: https://github.com/shakacode/cypress-on-rails/issues/20

According to [this list](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt) there are a few ranges of ports that are not assigned, the closest to the current setting is 5016-5019, and this [wikipedia page](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) seems to confirm it.

The way I got port 5017 was by "rolling the dice" in pry console:

```rb
 >  (5016..5019).to_a
[
  5016,
  5017,
  5018,
  5019
]
 >  (5016..5019).to_a.sample
5017
```

I ran this code exactly once. :)

### CODE REVIEW

**Comment by yagudaev** [comment]
One consideration there would be having a larger range to pull-from in case `cypress-on-rails` starts supporting parallel test execution in conjunction with the `rspec-parallel` gem.

**Comment by grantspeelman** [comment]
if we going to change the port, I think it better if we choose the first available port after the default of 3000 that Ruby on Rails uses?

**Comment by vfonic** [comment]
@yagudaev That's a great idea! I'm overwhelmed by all the "available port ranges" documentation. Where can I find a good port range easily? Do you have any suggestions which port should the gem default to?

@grantspeelman what are the benefits of choosing first available port after the default 3000?

**Comment by yagudaev** [comment]
@vfonic honestly you are right looking at the list it all seems pretty arbitrary. I looked at how Cucumber chooses ports, but it also seems arbitrary.

So in that sense, since the main rails app usually runs on 3000 and some other related systems might be on 300x port. I'd agree with @grantspeelman probably using the 4000+ range is a good default. Of course, it is all configurable so a user can choose to change it if it conflicts with something.

**Comment by grantspeelman** [comment]
Hmmm, maybe I am over thinking it :smile: 
5017 it is :+1:

**Comment by grantspeelman** [comment]
@vfonic if you can update the CHANGELOG.md then this should be good to merge.
Don't have to do a new version, only add to the top this change.

**Comment by vfonic** [comment]
I took some time to dig through this list of ports: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt

It's actually relatively easy once you search by "Unassigned" (in HTML format):
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=unassigned&page=2

Considering parallel tests possibility, it might be good to find a port range that has more than 4 port numbers available? (`5016-5019`)

Perhaps at least 8+ port numbers would be a better choice?

<details><summary>Here are some of our options:</summary>

- `4380-4388` - 9 ports
- `4434-4440` - 7 ports
- `4459-4483` - 25 ports
- `4489-4499` - 11 ports
- `4503-4533` - 31 ports
- `4539-4544` - 6 ports
- `4574-4589` - 16 ports
- `4606-4620` - 15 ports
- `4622-4645` - 24 ports
- `4647-4657` - 11 ports
- `4693-4699` - 7 ports
- `4705-4710` - 6 ports
- `4712-4724` - 13 ports
- `4757-4773` - 17 ports
- `4775-4783` - 9 ports
- `4792-4799` - 8 ports
- `4805-4826` - 22 ports
- `4828-4836` - 9 ports
- `4852-4866` - 15 ports
- `4872-4875` - 4 ports
- `4890-4893` - 4 ports
- `4895-4898` - 4 ports
- `4903-4911` - 9 ports
- `4916-4935` - 20 ports
- `4943-4948` - 6 ports
- `4954-4966` - 13 ports
- `4972-4979` - 8 ports
- `4992-4998` - 7 ports
- `5016-5019` - 4 ports
- `5035-5041` - 7 ports
- `5095-5098` - 4 ports
- `5121-5132` - 12 ports
- `5138-5144` - 7 ports
- `5173-5189` - 17 ports
- `5204-5208` - 5 ports
- `5210-5214` - 5 ports
- `5216-5220` - 5 ports
- `5238-5244` - 7 ports
- `5255-5263` - 9 ports
- `5273-5279` - 7 ports
- `5283-5297` - 15 ports
</details>

What do you think?

/cc @spaghetticode

**Comment by grantspeelman** [comment]
I don't see any plans for Cypress to allow parallel tests on a single host, so don't think it's something we should worry about.

**Comment by vfonic** [comment]
Aye, sir! I updated the `CHANGELOG` by amending the commit and force-pushed the changes to my fork/branch.

**Comment by yagudaev** [comment]
@grantspeelman cypress.io direction is driven by their need to make revenue. The cypress dashboard actually does the tests splitting. However, it is completely unnecessary if your CI service can already split tests to multiple hosts.

This would be really useful for local testing, we often run rspec parallel locally when we do big changes that affect a lot of the app. It is really nice. There is no reason this couldn't be part of the rspec parallel gem. I might take a stab at it myself.

**Comment by justin808** [comment]
@grantspeelman why was the port not set to 3000, the default for Rails apps?

**Comment by grantspeelman** [comment]
basically so you can have you dev environment running and cypress test environment running at the same time.
I think it ended up being port 5002 because the project that i extract the code from ran it's rails server on port 5001, so 5002 was the next number :)

**Pull request merged**
